// ============================================================
// © 2025 AIVaultCo — ExcuseMachine™ — All Rights Reserved
// aivaultco.com | Unauthorized reproduction prohibited.
// ============================================================

import { useState, useEffect } from "react";

const APP_VERSION   = "1.0.0";
const DOMAIN        = "aivaultco.com";
const BRAND         = "ExcuseMachine™";
const WATERMARK     = `\n\n— Generated by ${BRAND} (${DOMAIN})`;
const COPYRIGHT     = `© ${new Date().getFullYear()} AIVaultCo — ${BRAND} — All Rights Reserved`;

// ─── STRIPE PAYMENT LINKS ────────────────────────────────────
// SETUP (5 min):
// 1. Go to dashboard.stripe.com → sign up free
// 2. Payments → Payment Links → + New
// 3. Create one link per package below, name them Starter / Pro / Mega
// 4. For each link: Settings → After payment → Redirect to:
//    https://aivaultco.com?pkg=starter   (or pro / mega)
// 5. Paste your link URLs below — that's it. Stripe handles everything.
const STRIPE_LINKS = {
  starter: "https://buy.stripe.com/REPLACE_STARTER_LINK",   // $0.99 → 5 credits
  pro:     "https://buy.stripe.com/REPLACE_PRO_LINK",       // $2.99 → 20 credits
  mega:    "https://buy.stripe.com/REPLACE_MEGA_LINK",      // $6.99 → 60 credits
};

const PACKAGES = [
  { id:"starter", label:"Starter",  credits:5,  price:"$0.99", note:"Try it out",       popular:false },
  { id:"pro",     label:"Pro",      credits:20, price:"$2.99", note:"Most popular",      popular:true  },
  { id:"mega",    label:"Mega",     credits:60, price:"$6.99", note:"Best value · save 40%", popular:false },
];

// ─── EXCUSE DATA ─────────────────────────────────────────────
const FREE_EXCUSES = [
  { text:"I'm running late — traffic is moving backwards today.", cat:"Work" },
  { text:"My alarm didn't go off because I forgot to turn it back on after the weekend.", cat:"Work" },
  { text:"I spilled coffee on myself and had to change before leaving.", cat:"Work" },
  { text:"My boss from my old job needed paperwork. It took longer than expected.", cat:"Work" },
  { text:"My kid's school asked me to come by unexpectedly.", cat:"Work" },
  { text:"My bus broke down and the next one never showed.", cat:"School" },
  { text:"I wasn't feeling well earlier but I'm okay now.", cat:"School" },
  { text:"I overslept because I stayed up studying.", cat:"School" },
  { text:"My family needed help with something urgent.", cat:"School" },
  { text:"I needed to finish a personal assignment before leaving.", cat:"School" },
  { text:"A family member needed help moving something heavy.", cat:"Family" },
  { text:"My partner wasn't feeling well and needed a moment.", cat:"Family" },
  { text:"My pet got out and I had to chase it down.", cat:"Family" },
  { text:"I had to wait for a delivery that required a signature.", cat:"Family" },
  { text:"We had a sudden family situation that delayed me.", cat:"Family" },
  { text:"Sorry, I double-booked myself by accident.", cat:"Polite" },
  { text:"Something unexpected came up — can we reschedule?", cat:"Polite" },
  { text:"I'm not feeling my best today — better to postpone.", cat:"Polite" },
  { text:"I'm running behind, but I'm on my way.", cat:"Polite" },
  { text:"I had a quick issue to handle — I'll be there shortly.", cat:"Polite" },
  { text:"I can't come — my couch and I are in a committed relationship today.", cat:"Funny" },
  { text:"My dog hid my keys to keep me home.", cat:"Funny" },
  { text:"I accidentally took nighttime cold medicine this morning.", cat:"Funny" },
  { text:"I got trapped in a YouTube rabbit hole and lost track of time.", cat:"Funny" },
  { text:"I was abducted by responsibilities and only just escaped.", cat:"Funny" },
  { text:"I forgot what day it was.", cat:"Random" },
  { text:"My phone died and I didn't see the time.", cat:"Random" },
  { text:"My ride canceled last minute.", cat:"Random" },
  { text:"I'm stuck behind someone driving 5 mph.", cat:"Random" },
  { text:"My GPS glitched and sent me in the wrong direction.", cat:"Random" },
  { text:"Someone parked behind me and blocked my car.", cat:"Random" },
  { text:"My pet knocked something over and I had to clean it up.", cat:"Family" },
  { text:"My internet went down and delayed me leaving.", cat:"Random" },
  { text:"I had a quick call I couldn't leave.", cat:"Polite" },
  { text:"Unexpected visitors showed up briefly.", cat:"Family" },
];

const FREE_CATS    = ["All","Work","School","Family","Polite","Funny","Random"];
const PREMIUM_CATS = ["Breakup","Relationship","Emergency","Extreme","Creative","Savage"];

const EMOJI = {
  All:"✨", Work:"💼", School:"📚", Family:"👨‍👩‍👧", Polite:"🤝",
  Funny:"😂", Random:"🎲", Breakup:"💔", Relationship:"💬",
  Emergency:"🚨", Extreme:"⚡", Creative:"🎨", Savage:"🔥",
};

const AI_PROMPTS = {
  Breakup:      "Write one dramatic, emotionally convincing breakup excuse. Specific, believable, no clichés. Return the excuse only — no intro, no quotes.",
  Relationship: "Write one clever excuse to skip a relationship obligation (date night, meeting their parents, an anniversary plan). Creative and specific. Return the excuse only.",
  Emergency:    "Write one fake but completely plausible urgent emergency excuse. Make it dramatic but believable. Return the excuse only.",
  Extreme:      "Write one wildly absurd, over-the-top excuse that is darkly funny and extreme. Return the excuse only.",
  Creative:     "Write one uniquely imaginative excuse that nobody would ever anticipate. Surprising and original. Return the excuse only.",
  Savage:       "Write one savage, brutally blunt excuse with zero regard for feelings. Unapologetic. Return the excuse only.",
};

// ─── LOCAL STORAGE CREDIT SYSTEM ─────────────────────────────
const KEYS = { credits:"em_credits_v1", trials:"em_trials_v1" };
const FREE_TRIALS = 3;
const storage = {
  get: (k) => { try { return parseInt(localStorage.getItem(k)||"0",10); } catch { return 0; } },
  set: (k,v) => { try { localStorage.setItem(k,String(v)); } catch {} },
};

// ─── HELPERS ─────────────────────────────────────────────────
const pick = (arr) => arr[Math.floor(Math.random()*arr.length)];

// ─── APP ─────────────────────────────────────────────────────
export default function App() {
  const [tab, setTab]             = useState("free");
  const [freeCat, setFreeCat]     = useState("All");
  const [premCat, setPremCat]     = useState("Breakup");
  const [excuse, setExcuse]       = useState(null);
  const [loading, setLoading]     = useState(false);
  const [copied, setCopied]       = useState(false);
  const [credits, setCredits]     = useState(storage.get(KEYS.credits));
  const [trials, setTrials]       = useState(storage.get(KEYS.trials));
  const [modal, setModal]         = useState(false);   // paywall modal
  const [toast, setToast]         = useState(null);    // success toast
  const [cardIn, setCardIn]       = useState(false);

  const trialsLeft      = Math.max(0, FREE_TRIALS - trials);
  const hasPremium      = credits > 0 || trialsLeft > 0;

  // ── Detect return from Stripe ──
  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const pkg    = params.get("pkg");
    if (pkg) {
      const found = PACKAGES.find(p => p.id === pkg);
      if (found) {
        const next = storage.get(KEYS.credits) + found.credits;
        storage.set(KEYS.credits, next);
        setCredits(next);
        window.history.replaceState({}, "", "/");
        showToast(`✦ ${found.credits} credits added! Welcome to Premium.`);
      }
    }
  }, []);

  const showToast = (msg) => {
    setToast(msg);
    setTimeout(() => setToast(null), 4000);
  };

  const showCard = (text, cat, premium) => {
    setCardIn(false);
    setTimeout(() => { setExcuse({ text, cat, premium }); setCardIn(true); }, 160);
  };

  const spendCredit = () => {
    if (credits > 0) {
      const n = credits - 1;
      storage.set(KEYS.credits, n);
      setCredits(n);
    } else {
      const n = trials + 1;
      storage.set(KEYS.trials, n);
      setTrials(n);
    }
  };

  const generateFree = () => {
    const pool = freeCat === "All" ? FREE_EXCUSES : FREE_EXCUSES.filter(e => e.cat === freeCat);
    const e    = pick(pool);
    showCard(e.text, e.cat, false);
  };

  const generatePremium = async () => {
    if (!hasPremium) { setModal(true); return; }
    setLoading(true);
    spendCredit();
    try {
      const res  = await fetch("https://api.anthropic.com/v1/messages", {
        method:  "POST",
        headers: { "Content-Type":"application/json" },
        body:    JSON.stringify({
          model:      "claude-sonnet-4-20250514",
          max_tokens: 1000,
          messages:   [{ role:"user", content: AI_PROMPTS[premCat] }],
        }),
      });
      const data = await res.json();
      const text = data.content?.map(b=>b.text||"").join("").trim().replace(/^["'""'']+|["'""'']+$/g,"");
      showCard(text, premCat, true);
    } catch {
      showCard("Even our AI needed an excuse today. Try again!", premCat, true);
    }
    setLoading(false);
  };

  const copy = () => {
    if (!excuse) return;
    navigator.clipboard.writeText(excuse.text + WATERMARK);
    setCopied(true);
    setTimeout(() => setCopied(false), 2200);
  };

  const openStripe = (pkg) => {
    const link = STRIPE_LINKS[pkg.id];
    window.open(link, "_blank");
  };

  // ─── RENDER ────────────────────────────────────────────────
  return (
    <div style={S.root}>
      {/* Ambient */}
      <div style={S.glowTop} />
      <div style={S.glowBot} />

      {/* Toast */}
      {toast && (
        <div style={S.toast}>{toast}</div>
      )}

      <div style={S.wrap}>

        {/* ── HEADER ── */}
        <header style={S.header}>
          <div style={S.superLabel}>★ Official ★</div>
          <h1 style={S.h1a}>Excuse</h1>
          <h1 style={S.h1b}>Machine™</h1>
          <p style={S.tagline}>Professionally crafted alibis for every occasion</p>

          {/* Credit counter */}
          <div style={S.creditBar}>
            <span style={S.creditIcon}>✦</span>
            <span style={S.creditNum}>{credits}</span>
            <span style={S.creditLabel}>credits</span>
            {trialsLeft > 0 && <span style={S.trialBadge}>{trialsLeft} free {trialsLeft===1?"try":"tries"}</span>}
            <button style={S.buyBtn} onClick={() => setModal(true)}>+ Buy</button>
          </div>
        </header>

        {/* ── TAB TOGGLE ── */}
        <div style={S.tabs}>
          {[["free","Free Excuses"],["premium","✦ Premium AI"]].map(([id,label])=>(
            <button key={id} onClick={()=>setTab(id)} style={{
              ...S.tab,
              background: tab===id ? (id==="premium" ? "#f5a623" : "#1e1e2e") : "transparent",
              color:      tab===id ? (id==="premium" ? "#080810" : "#f0ebe0") : "#555",
              fontWeight: tab===id ? "700" : "400",
            }}>{label}</button>
          ))}
        </div>

        {/* ── CATEGORY PILLS ── */}
        <div style={S.pills}>
          {(tab==="free" ? FREE_CATS : PREMIUM_CATS).map(cat=>{
            const active = tab==="free" ? freeCat===cat : premCat===cat;
            return (
              <button key={cat} onClick={()=> tab==="free" ? setFreeCat(cat) : setPremCat(cat)} style={{
                ...S.pill,
                borderColor: active ? "#f5a623" : "#1e1e2e",
                background:  active ? "rgba(245,166,35,0.1)" : "transparent",
                color:       active ? "#f5a623" : "#555",
              }}>{EMOJI[cat]} {cat}</button>
            );
          })}
        </div>

        {/* ── GENERATE BUTTON ── */}
        <div style={{ textAlign:"center", marginBottom:"32px" }}>
          <button
            onClick={tab==="free" ? generateFree : generatePremium}
            disabled={loading}
            style={{
              ...S.genBtn,
              background: tab==="premium"
                ? "linear-gradient(135deg,#f5a623,#d4751a)"
                : "linear-gradient(135deg,#e8e3d8,#c8c3b8)",
              boxShadow: tab==="premium" ? "0 0 50px rgba(245,166,35,0.2)" : "none",
              opacity: loading ? 0.65 : 1,
              cursor:  loading ? "not-allowed" : "pointer",
            }}>
            {loading ? "Crafting your excuse…" : tab==="premium" ? "✦ Generate Premium Excuse" : "Generate Excuse"}
          </button>

          {tab==="premium" && !hasPremium && (
            <p style={S.noCredits}>
              No credits — <button style={S.inlineLink} onClick={()=>setModal(true)}>buy more</button>
            </p>
          )}
          {tab==="premium" && trialsLeft>0 && credits===0 && (
            <p style={S.trialNote}>{trialsLeft} free premium {trialsLeft===1?"try":"tries"} remaining</p>
          )}
        </div>

        {/* ── EXCUSE CARD ── */}
        <div style={{ opacity:cardIn?1:0, transform:cardIn?"translateY(0)":"translateY(18px)", transition:"opacity 0.35s ease, transform 0.35s ease" }}>
          {excuse && (
            <div style={{
              ...S.card,
              background:  excuse.premium ? "linear-gradient(160deg,#131009,#0e0b06)" : "#0f0f1a",
              borderColor: excuse.premium ? "rgba(245,166,35,0.3)" : "#1a1a28",
              boxShadow:   excuse.premium ? "0 0 60px rgba(245,166,35,0.08), inset 0 1px 0 rgba(245,166,35,0.08)" : "0 4px 40px rgba(0,0,0,0.5)",
            }}>
              {excuse.premium && <div style={S.premiumBadge}>✦ Premium</div>}
              <div style={{ ...S.catLabel, color: excuse.premium ? "#f5a623" : "#444" }}>
                {EMOJI[excuse.cat]} {excuse.cat}
              </div>
              <p style={S.excuseText}>"{excuse.text}"</p>
              <div style={S.cardActions}>
                <button onClick={copy} style={{ ...S.cardBtn, borderColor: copied?"rgba(245,166,35,0.4)":"#1e1e2e", color: copied?"#f5a623":"#666", background: copied?"rgba(245,166,35,0.08)":"transparent" }}>
                  {copied ? "✓ Copied!" : "📋 Copy"}
                </button>
                <button onClick={tab==="free"?generateFree:generatePremium} disabled={loading} style={{ ...S.cardBtn, color:"#666" }}>
                  ↻ Another
                </button>
              </div>
              <p style={S.cardWatermark}>{COPYRIGHT}</p>
            </div>
          )}
        </div>

        {/* ── HOW IT WORKS (social proof / conversion) ── */}
        {!excuse && (
          <div style={S.howItWorks}>
            <div style={S.howGrid}>
              {[
                ["🎲","Instant","Pick a category and generate a ready-to-send excuse in seconds."],
                ["✦","AI-Powered","Premium excuses are uniquely crafted by AI — no two alike."],
                ["📋","Copy & Go","One tap copies your excuse with your name watermarked."],
              ].map(([icon,title,desc])=>(
                <div key={title} style={S.howCard}>
                  <div style={S.howIcon}>{icon}</div>
                  <div style={S.howTitle}>{title}</div>
                  <div style={S.howDesc}>{desc}</div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* ── FOOTER ── */}
        <footer style={S.footer}>
          <div>{COPYRIGHT}</div>
          <div style={{ marginTop:"4px", color:"#1e1e2e" }}>v{APP_VERSION} · {DOMAIN}</div>
        </footer>
      </div>

      {/* ── PAYWALL MODAL ── */}
      {modal && (
        <div style={S.overlay} onClick={()=>setModal(false)}>
          <div style={S.modal} onClick={e=>e.stopPropagation()}>
            <div style={{ textAlign:"center", marginBottom:"28px" }}>
              <div style={{ fontSize:"36px", marginBottom:"8px" }}>✦</div>
              <h2 style={S.modalTitle}>Go Premium</h2>
              <p style={S.modalSub}>AI-generated excuses, unique every time.<br/>No subscription. No account. Just credits.</p>
            </div>

            <div style={{ display:"flex", flexDirection:"column", gap:"10px", marginBottom:"20px" }}>
              {PACKAGES.map(pkg=>(
                <button key={pkg.id} onClick={()=>openStripe(pkg)} style={{
                  ...S.pkgBtn,
                  borderColor: pkg.popular ? "#f5a623" : "#1e1e2e",
                  background:  pkg.popular ? "rgba(245,166,35,0.07)" : "transparent",
                }}>
                  <div style={{ textAlign:"left" }}>
                    <div style={{ display:"flex", alignItems:"center", gap:"8px" }}>
                      <span style={{ fontSize:"15px", fontWeight:"700", color:"#f0ebe0" }}>{pkg.label}</span>
                      {pkg.popular && <span style={S.popularTag}>BEST VALUE</span>}
                    </div>
                    <div style={{ fontSize:"11px", color:"#555", marginTop:"2px" }}>{pkg.credits} credits · {pkg.note}</div>
                  </div>
                  <div style={{ fontSize:"18px", fontWeight:"800", color: pkg.popular?"#f5a623":"#f0ebe0" }}>{pkg.price}</div>
                </button>
              ))}
            </div>

            <p style={S.stripeNote}>🔒 Secure checkout by Stripe · Instant delivery · No account needed</p>
            <button onClick={()=>setModal(false)} style={S.closeBtn}>Maybe later</button>
          </div>
        </div>
      )}

      <style>{`
        * { box-sizing:border-box; }
        ::selection { background:rgba(245,166,35,0.25); }
        body { margin:0; }
        button { transition: opacity 0.15s, transform 0.12s; }
        button:hover:not(:disabled) { opacity:0.82; }
        button:active:not(:disabled) { transform:scale(0.97); }
        @keyframes slideDown { from{opacity:0;transform:translateY(-12px)} to{opacity:1;transform:translateY(0)} }
        @keyframes fadeIn    { from{opacity:0} to{opacity:1} }
      `}</style>
    </div>
  );
}

// ─── STYLES ──────────────────────────────────────────────────
const S = {
  root:        { minHeight:"100vh", background:"#080810", fontFamily:"'Georgia','Times New Roman',serif", color:"#f0ebe0", position:"relative", overflow:"hidden" },
  glowTop:     { position:"fixed", top:0, left:0, right:0, bottom:0, background:"radial-gradient(ellipse 70% 40% at 50% 0%,rgba(245,166,35,0.09),transparent)", pointerEvents:"none", zIndex:0 },
  glowBot:     { position:"fixed", bottom:0, left:0, right:0, height:"300px", background:"radial-gradient(ellipse 50% 100% at 50% 100%,rgba(180,40,40,0.06),transparent)", pointerEvents:"none", zIndex:0 },
  toast:       { position:"fixed", top:"20px", left:"50%", transform:"translateX(-50%)", background:"#f5a623", color:"#080810", padding:"12px 24px", borderRadius:"100px", fontSize:"14px", fontWeight:"700", zIndex:200, animation:"slideDown 0.3s ease", whiteSpace:"nowrap" },
  wrap:        { maxWidth:"620px", margin:"0 auto", padding:"0 18px 80px", position:"relative", zIndex:1 },
  header:      { textAlign:"center", paddingTop:"50px", paddingBottom:"28px" },
  superLabel:  { fontSize:"11px", letterSpacing:"0.4em", color:"#f5a623", textTransform:"uppercase", marginBottom:"12px", fontFamily:"monospace" },
  h1a:         { margin:0, lineHeight:1, fontSize:"clamp(3rem,10vw,5.8rem)", fontWeight:"normal", letterSpacing:"-0.02em" },
  h1b:         { margin:0, lineHeight:1, fontSize:"clamp(3rem,10vw,5.8rem)", fontWeight:"bold", fontStyle:"italic", color:"#f5a623", letterSpacing:"-0.02em" },
  tagline:     { color:"#555", marginTop:"14px", fontSize:"14px", fontStyle:"italic" },
  creditBar:   { display:"inline-flex", alignItems:"center", gap:"8px", marginTop:"18px", background:"rgba(245,166,35,0.07)", border:"1px solid rgba(245,166,35,0.18)", borderRadius:"100px", padding:"7px 18px", fontSize:"13px" },
  creditIcon:  { color:"#f5a623" },
  creditNum:   { color:"#f5a623", fontWeight:"800" },
  creditLabel: { color:"#555" },
  trialBadge:  { color:"#444", fontSize:"11px" },
  buyBtn:      { background:"#f5a623", color:"#080810", border:"none", borderRadius:"100px", padding:"4px 14px", fontSize:"11px", fontWeight:"900", cursor:"pointer", letterSpacing:"0.05em" },
  tabs:        { display:"flex", borderRadius:"12px", overflow:"hidden", border:"1px solid #1e1e2e", marginBottom:"24px" },
  tab:         { flex:1, padding:"12px", border:"none", cursor:"pointer", fontSize:"14px", fontFamily:"Georgia,serif", transition:"all 0.2s" },
  pills:       { display:"flex", flexWrap:"wrap", gap:"7px", justifyContent:"center", marginBottom:"26px" },
  pill:        { padding:"6px 15px", borderRadius:"100px", border:"1px solid", fontSize:"12px", cursor:"pointer", transition:"all 0.15s", fontFamily:"Georgia,serif" },
  genBtn:      { padding:"17px 52px", borderRadius:"12px", border:"none", color:"#080810", fontSize:"16px", fontWeight:"800", letterSpacing:"0.03em", fontFamily:"Georgia,serif" },
  noCredits:   { color:"#f5a623", fontSize:"13px", marginTop:"10px", fontStyle:"italic" },
  inlineLink:  { background:"none", border:"none", color:"#f5a623", textDecoration:"underline", cursor:"pointer", fontSize:"13px", fontFamily:"Georgia,serif", padding:0 },
  trialNote:   { color:"#444", fontSize:"12px", marginTop:"8px", fontStyle:"italic" },
  card:        { borderRadius:"20px", padding:"36px", border:"1px solid", position:"relative" },
  premiumBadge:{ position:"absolute", top:"-1px", left:"50%", transform:"translateX(-50%)", background:"linear-gradient(90deg,#f5a623,#d4751a)", color:"#080810", fontSize:"9px", fontWeight:"900", letterSpacing:"0.25em", padding:"4px 18px", borderRadius:"0 0 8px 8px", textTransform:"uppercase" },
  catLabel:    { fontSize:"10px", letterSpacing:"0.3em", textTransform:"uppercase", marginBottom:"16px", fontFamily:"monospace" },
  excuseText:  { fontSize:"clamp(1rem,2.5vw,1.2rem)", lineHeight:1.7, fontStyle:"italic", margin:"0 0 24px", color:"#f0ebe0" },
  cardActions: { display:"flex", gap:"10px", marginBottom:"16px" },
  cardBtn:     { flex:1, padding:"10px", borderRadius:"9px", border:"1px solid", background:"transparent", fontSize:"13px", cursor:"pointer", fontFamily:"Georgia,serif", transition:"all 0.2s" },
  cardWatermark:{ fontSize:"10px", color:"#1e1e2a", textAlign:"center", margin:0, letterSpacing:"0.06em" },
  howItWorks:  { marginTop:"40px" },
  howGrid:     { display:"grid", gridTemplateColumns:"repeat(auto-fit,minmax(160px,1fr))", gap:"12px" },
  howCard:     { background:"#0f0f1a", border:"1px solid #1a1a28", borderRadius:"16px", padding:"24px 18px", textAlign:"center" },
  howIcon:     { fontSize:"24px", marginBottom:"10px" },
  howTitle:    { fontSize:"14px", fontWeight:"700", color:"#f0ebe0", marginBottom:"6px" },
  howDesc:     { fontSize:"12px", color:"#555", lineHeight:1.5 },
  footer:      { textAlign:"center", marginTop:"60px", color:"#2a2a3a", fontSize:"11px", letterSpacing:"0.07em", lineHeight:1.8 },
  overlay:     { position:"fixed", inset:0, background:"rgba(0,0,0,0.85)", backdropFilter:"blur(8px)", zIndex:100, display:"flex", alignItems:"center", justifyContent:"center", padding:"18px", animation:"fadeIn 0.2s ease" },
  modal:       { background:"#0e0e18", border:"1px solid rgba(245,166,35,0.25)", borderRadius:"24px", padding:"40px 28px", maxWidth:"420px", width:"100%", boxShadow:"0 0 80px rgba(245,166,35,0.12)" },
  modalTitle:  { margin:0, fontSize:"1.7rem", color:"#f5a623", fontStyle:"italic" },
  modalSub:    { color:"#555", fontSize:"14px", marginTop:"8px", lineHeight:1.6 },
  pkgBtn:      { display:"flex", alignItems:"center", justifyContent:"space-between", padding:"16px 18px", borderRadius:"14px", border:"1px solid", cursor:"pointer", transition:"all 0.15s", fontFamily:"Georgia,serif", width:"100%" },
  popularTag:  { background:"#f5a623", color:"#080810", fontSize:"9px", fontWeight:"900", padding:"2px 8px", borderRadius:"100px", letterSpacing:"0.1em" },
  stripeNote:  { textAlign:"center", fontSize:"11px", color:"#333", lineHeight:1.6, marginBottom:"16px" },
  closeBtn:    { display:"block", width:"100%", padding:"10px", background:"none", border:"1px solid #1e1e2e", borderRadius:"10px", color:"#444", fontSize:"13px", cursor:"pointer", fontFamily:"Georgia,serif" },
};
